/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PaymentHistoryRouteImport } from './routes/payment-history'
import { Route as PaymentFailureRouteImport } from './routes/payment-failure'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackOrderOrderIdRouteImport } from './routes/track-order.$orderId'
import { Route as RestaurantIdRouteImport } from './routes/restaurant.$id'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as Oauth2RedirectRouteImport } from './routes/oauth2.redirect'
import { Route as FoodIdRouteImport } from './routes/food.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentHistoryRoute = PaymentHistoryRouteImport.update({
  id: '/payment-history',
  path: '/payment-history',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailureRoute = PaymentFailureRouteImport.update({
  id: '/payment-failure',
  path: '/payment-failure',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderOrderIdRoute = TrackOrderOrderIdRouteImport.update({
  id: '/track-order/$orderId',
  path: '/track-order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantIdRoute = RestaurantIdRouteImport.update({
  id: '/restaurant/$id',
  path: '/restaurant/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const Oauth2RedirectRoute = Oauth2RedirectRouteImport.update({
  id: '/oauth2/redirect',
  path: '/oauth2/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodIdRoute = FoodIdRouteImport.update({
  id: '/food/$id',
  path: '/food/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payment-failure': typeof PaymentFailureRoute
  '/payment-history': typeof PaymentHistoryRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/restaurants': typeof RestaurantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/wishlist': typeof WishlistRoute
  '/food/$id': typeof FoodIdRoute
  '/oauth2/redirect': typeof Oauth2RedirectRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/track-order/$orderId': typeof TrackOrderOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payment-failure': typeof PaymentFailureRoute
  '/payment-history': typeof PaymentHistoryRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/restaurants': typeof RestaurantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/wishlist': typeof WishlistRoute
  '/food/$id': typeof FoodIdRoute
  '/oauth2/redirect': typeof Oauth2RedirectRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/track-order/$orderId': typeof TrackOrderOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payment-failure': typeof PaymentFailureRoute
  '/payment-history': typeof PaymentHistoryRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/restaurants': typeof RestaurantsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/wishlist': typeof WishlistRoute
  '/food/$id': typeof FoodIdRoute
  '/oauth2/redirect': typeof Oauth2RedirectRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/track-order/$orderId': typeof TrackOrderOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/offers'
    | '/orders'
    | '/payment-failure'
    | '/payment-history'
    | '/payment-success'
    | '/profile'
    | '/register'
    | '/restaurants'
    | '/sitemap.xml'
    | '/support'
    | '/wishlist'
    | '/food/$id'
    | '/oauth2/redirect'
    | '/orders/$orderId'
    | '/restaurant/$id'
    | '/track-order/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/offers'
    | '/orders'
    | '/payment-failure'
    | '/payment-history'
    | '/payment-success'
    | '/profile'
    | '/register'
    | '/restaurants'
    | '/sitemap.xml'
    | '/support'
    | '/wishlist'
    | '/food/$id'
    | '/oauth2/redirect'
    | '/orders/$orderId'
    | '/restaurant/$id'
    | '/track-order/$orderId'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/offers'
    | '/orders'
    | '/payment-failure'
    | '/payment-history'
    | '/payment-success'
    | '/profile'
    | '/register'
    | '/restaurants'
    | '/sitemap.xml'
    | '/support'
    | '/wishlist'
    | '/food/$id'
    | '/oauth2/redirect'
    | '/orders/$orderId'
    | '/restaurant/$id'
    | '/track-order/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  OffersRoute: typeof OffersRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PaymentFailureRoute: typeof PaymentFailureRoute
  PaymentHistoryRoute: typeof PaymentHistoryRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RestaurantsRoute: typeof RestaurantsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  WishlistRoute: typeof WishlistRoute
  FoodIdRoute: typeof FoodIdRoute
  Oauth2RedirectRoute: typeof Oauth2RedirectRoute
  RestaurantIdRoute: typeof RestaurantIdRoute
  TrackOrderOrderIdRoute: typeof TrackOrderOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-history': {
      id: '/payment-history'
      path: '/payment-history'
      fullPath: '/payment-history'
      preLoaderRoute: typeof PaymentHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-failure': {
      id: '/payment-failure'
      path: '/payment-failure'
      fullPath: '/payment-failure'
      preLoaderRoute: typeof PaymentFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order/$orderId': {
      id: '/track-order/$orderId'
      path: '/track-order/$orderId'
      fullPath: '/track-order/$orderId'
      preLoaderRoute: typeof TrackOrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$id': {
      id: '/restaurant/$id'
      path: '/restaurant/$id'
      fullPath: '/restaurant/$id'
      preLoaderRoute: typeof RestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/oauth2/redirect': {
      id: '/oauth2/redirect'
      path: '/oauth2/redirect'
      fullPath: '/oauth2/redirect'
      preLoaderRoute: typeof Oauth2RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/$id': {
      id: '/food/$id'
      path: '/food/$id'
      fullPath: '/food/$id'
      preLoaderRoute: typeof FoodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  OffersRoute: OffersRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PaymentFailureRoute: PaymentFailureRoute,
  PaymentHistoryRoute: PaymentHistoryRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RestaurantsRoute: RestaurantsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  WishlistRoute: WishlistRoute,
  FoodIdRoute: FoodIdRoute,
  Oauth2RedirectRoute: Oauth2RedirectRoute,
  RestaurantIdRoute: RestaurantIdRoute,
  TrackOrderOrderIdRoute: TrackOrderOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
